FROM clowder/extractors-simple-extractor-python3:onbuild

ENV EXTRACTION_MODULE="tensorflow_extractor"
ENV EXTRACTION_FUNC="extract"

#RUN pip install --upgrade pip

COPY tensorflow_model_mnist.h5 tensorflow_model_mnist.h5
