name: mnist-setup
channels:
  - conda-forge
dependencies:
  - python=3.6
  - absl-py==0.5.0
  - astor==0.7.1
  - certifi==2018.11.29
  - chardet==3.0.4
  - cycler==0.10.0
  - gast==0.2.0
  - grpcio
  - h5py==2.8.0
  - idna==2.8
  - Keras-Applications==1.0.6
  - Keras-Preprocessing==1.0.5
  - kiwisolver==1.0.1
  - Markdown==3.0.1
  - matplotlib==3.0.2
  - mock==2.0.0
  - numpy==1.15.2
  - pbr==5.1.2
  - Pillow==5.4.1
  - protobuf==3.6.1
  - pyparsing==2.3.1
  - python-dateutil==2.8.0
  - six==1.11.0
  - tensorboard==1.13.0
  - tensorflow==1.13.1
  - tensorflow-estimator==1.13.0
  - termcolor==1.1.0
  - urllib3==1.24.1
  - Werkzeug==0.14.1